"""
LTA carpark static lookup table.

Loads lta_carparks.csv at import time and exposes ``LTA_CARPARK_LOOKUP``,
a dict keyed by raw CarParkID (e.g. ``"B0020"``) for O(1) request-time
metadata lookups without hitting the LTA API.

The CSV is generated by running:
    python src/data_pipeline/fetch_lta_carparks.py

If the CSV is absent (e.g. first checkout before the pipeline has been
run), the lookup will be an empty dict and the backend degrades
gracefully to HDB-only results.
"""
from __future__ import annotations

import csv
from pathlib import Path

_DATA_DIR = Path(__file__).parent
_CSV = _DATA_DIR / "lta_carparks.csv"


def _load() -> dict[str, dict]:
    lookup: dict[str, dict] = {}
    if not _CSV.exists():
        return lookup

    with open(_CSV, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            cp_id = row.get("carpark_id", "").strip()
            if not cp_id:
                continue
            try:
                lookup[cp_id] = {
                    "development": row.get("development", "").strip(),
                    "lat": float(row["lat"]),
                    "lng": float(row["lng"]),
                }
            except (ValueError, KeyError):
                continue

    return lookup


# Loaded once at import time — fast O(1) lookups at request time
LTA_CARPARK_LOOKUP: dict[str, dict] = _load()
